import type { INodePropertyOptions } from 'n8n-workflow';

// Source: https://developers.facebook.com/documentation/business-messaging/whatsapp/templates/supported-languages
export const templateLanguageOptions: INodePropertyOptions[] = [
	{ name: 'Afrikaans', value: 'af' },
	{ name: 'Albanian', value: 'sq' },
	{ name: 'Arabic', value: 'ar' },
	{ name: 'Arabic (Egypt)', value: 'ar_EG' },
	{ name: 'Arabic (Lebanon)', value: 'ar_LB' },
	{ name: 'Arabic (Morocco)', value: 'ar_MA' },
	{ name: 'Arabic (Qatar)', value: 'ar_QA' },
	{ name: 'Arabic (UAE)', value: 'ar_AE' },
	{ name: 'Azerbaijani', value: 'az' },
	{ name: 'Belarusian', value: 'be_BY' },
	{ name: 'Bengali', value: 'bn' },
	{ name: 'Bengali (India)', value: 'bn_IN' },
	{ name: 'Bulgarian', value: 'bg' },
	{ name: 'Catalan', value: 'ca' },
	{ name: 'Chinese (China)', value: 'zh_CN' },
	{ name: 'Chinese (Hong Kong)', value: 'zh_HK' },
	{ name: 'Chinese (Taiwan)', value: 'zh_TW' },
	{ name: 'Croatian', value: 'hr' },
	{ name: 'Czech', value: 'cs' },
	{ name: 'Danish', value: 'da' },
	{ name: 'Dari', value: 'prs_AF' },
	{ name: 'Dutch', value: 'nl' },
	{ name: 'Dutch (Belgium)', value: 'nl_BE' },
	{ name: 'English', value: 'en' },
	{ name: 'English (Australia)', value: 'en_AU' },
	{ name: 'English (Canada)', value: 'en_CA' },
	{ name: 'English (Ghana)', value: 'en_GH' },
	{ name: 'English (India)', value: 'en_IN' },
	{ name: 'English (Ireland)', value: 'en_IE' },
	{ name: 'English (Jamaica)', value: 'en_JM' },
	{ name: 'English (Malaysia)', value: 'en_MY' },
	{ name: 'English (New Zealand)', value: 'en_NZ' },
	{ name: 'English (Qatar)', value: 'en_QA' },
	{ name: 'English (Singapore)', value: 'en_SG' },
	{ name: 'English (South Africa)', value: 'en_ZA' },
	{ name: 'English (UAE)', value: 'en_AE' },
	{ name: 'English (Uganda)', value: 'en_UG' },
	{ name: 'English (UK)', value: 'en_GB' },
	{ name: 'English (US)', value: 'en_US' },
	{ name: 'Estonian', value: 'et' },
	{ name: 'Filipino', value: 'fil' },
	{ name: 'Finnish', value: 'fi' },
	{ name: 'French', value: 'fr' },
	{ name: 'French (Belgium)', value: 'fr_BE' },
	{ name: 'French (Canada)', value: 'fr_CA' },
	{ name: 'French (Ivory Coast)', value: 'fr_CI' },
	{ name: 'French (Morocco)', value: 'fr_MA' },
	{ name: 'French (Switzerland)', value: 'fr_CH' },
	{ name: 'Georgian', value: 'ka' },
	{ name: 'German', value: 'de' },
	{ name: 'German (Austria)', value: 'de_AT' },
	{ name: 'German (Switzerland)', value: 'de_CH' },
	{ name: 'Greek', value: 'el' },
	{ name: 'Gujarati', value: 'gu' },
	{ name: 'Hausa', value: 'ha' },
	{ name: 'Hebrew', value: 'he' },
	{ name: 'Hindi', value: 'hi' },
	{ name: 'Hungarian', value: 'hu' },
	{ name: 'Indonesian', value: 'id' },
	{ name: 'Irish', value: 'ga' },
	{ name: 'Italian', value: 'it' },
	{ name: 'Japanese', value: 'ja' },
	{ name: 'Kannada', value: 'kn' },
	{ name: 'Kazakh', value: 'kk' },
	{ name: 'Kinyarwanda', value: 'rw_RW' },
	{ name: 'Korean', value: 'ko' },
	{ name: 'Kyrgyz (Kyrgyzstan)', value: 'ky_KG' },
	{ name: 'Lao', value: 'lo' },
	{ name: 'Latvian', value: 'lv' },
	{ name: 'Lithuanian', value: 'lt' },
	{ name: 'Macedonian', value: 'mk' },
	{ name: 'Malay', value: 'ms' },
	{ name: 'Malayalam', value: 'ml' },
	{ name: 'Marathi', value: 'mr' },
	{ name: 'Norwegian', value: 'nb' },
	{ name: 'Pashto', value: 'ps_AF' },
	{ name: 'Persian', value: 'fa' },
	{ name: 'Polish', value: 'pl' },
	{ name: 'Portuguese (Brazil)', value: 'pt_BR' },
	{ name: 'Portuguese (Portugal)', value: 'pt_PT' },
	{ name: 'Punjabi', value: 'pa' },
	{ name: 'Romanian', value: 'ro' },
	{ name: 'Russian', value: 'ru' },
	{ name: 'Serbian', value: 'sr' },
	{ name: 'Sinhala', value: 'si_LK' },
	{ name: 'Slovak', value: 'sk' },
	{ name: 'Slovenian', value: 'sl' },
	{ name: 'Spanish', value: 'es' },
	{ name: 'Spanish (Argentina)', value: 'es_AR' },
	{ name: 'Spanish (Chile)', value: 'es_CL' },
	{ name: 'Spanish (Colombia)', value: 'es_CO' },
	{ name: 'Spanish (Costa Rica)', value: 'es_CR' },
	{ name: 'Spanish (Dominican Republic)', value: 'es_DO' },
	{ name: 'Spanish (Ecuador)', value: 'es_EC' },
	{ name: 'Spanish (Honduras)', value: 'es_HN' },
	{ name: 'Spanish (Mexico)', value: 'es_MX' },
	{ name: 'Spanish (Panama)', value: 'es_PA' },
	{ name: 'Spanish (Peru)', value: 'es_PE' },
	{ name: 'Spanish (Spain)', value: 'es_ES' },
	{ name: 'Spanish (Uruguay)', value: 'es_UY' },
	{ name: 'Swahili', value: 'sw' },
	{ name: 'Swedish', value: 'sv' },
	{ name: 'Tamil', value: 'ta' },
	{ name: 'Telugu', value: 'te' },
	{ name: 'Thai', value: 'th' },
	{ name: 'Turkish', value: 'tr' },
	{ name: 'Ukrainian', value: 'uk' },
	{ name: 'Urdu', value: 'ur' },
	{ name: 'Uzbek', value: 'uz' },
	{ name: 'Vietnamese', value: 'vi' },
	{ name: 'Zulu', value: 'zu' },
];
